# $tasks['dr_seeds1'] = BuildStockpileTask.new('dr_seeds1', ['dr_dig_-2'], [1, 1, -2], 1, 3, 'dr_seeds')
# $tasks['dr_farm1'] = BuildFarmTask.new('dr_farm1', ['dr_dig_-2'], [2, 1, -2], 4, 5, [187,187,187,187])
# $tasks['dr_farm2'] = BuildFarmTask.new('dr_farm2', ['dr_dig_-2'], [6, 1, -2], 5, 5, [172,172,172,172])
# $tasks['fd_seeds1'] = BuildStockpileTask.new('fd_seeds1', ['fd_dig_-2'], [12, 1, -2], 1, 3, 'food_seeds')
# $tasks['fd_farm1'] = BuildFarmTask.new('fd_farm1', ['fd_dig_-2'], [13, 1, -2], 4, 5, [176,176,176,176])
# $tasks['fd_farm2'] = BuildFarmTask.new('fd_farm2', ['fd_dig_-2'], [17, 1, -2], 5, 5, [172,172,172,172])
# $tasks['cl_farm1'] = BuildFarmTask.new('cl_farm1', ['cl_dig_-2'], [26, 1, -2], 9, 5, [173,173,173,173])
# $tasks['cl_seeds1'] = BuildStockpileTask.new('cl_seeds1', ['cl_dig_-2'], [35, 1, -2], 1, 3, 'None')
# $tasks['dr_fert'] = BuildStockpileTask.new('dr_fert', ['dr_dig_-2'], [1, 5, -2], 1, 2, 'potash')
# $tasks['fd_fert'] = BuildStockpileTask.new('fd_fert', ['fd_dig_-2'], [12, 5, -2], 1, 2, 'potash')
# $tasks['cl_fert'] = BuildStockpileTask.new('cl_fert', ['cl_dig_-2'], [35, 5, -2], 1, 2, 'potash')
# $tasks['dr_farm3'] = BuildFarmTask.new('dr_farm3', ['dr_dig_-2'], [2, 6, -2], 4, 5, [176,176,176,176])
# $tasks['dr_farm4'] = BuildFarmTask.new('dr_farm4', ['dr_dig_-2'], [6, 6, -2], 5, 5, [174,174,174,174])
# $tasks['fd_farm3'] = BuildFarmTask.new('fd_farm3', ['fd_dig_-2'], [13, 6, -2], 4, 5, [175,175,175,175])
# $tasks['fd_farm4'] = BuildFarmTask.new('fd_farm4', ['fd_dig_-2'], [17, 6, -2], 5, 5, [174,174,174,174])
# $tasks['cl_farm2'] = BuildFarmTask.new('cl_farm2', ['cl_dig_-2'], [26, 6, -2], 9, 5, [187,187,187,187])
# $tasks['dr_seeds2'] = BuildStockpileTask.new('dr_seeds2', ['dr_dig_-2'], [1, 8, -2], 1, 3, 'dr_seeds')
# $tasks['fd_seeds2'] = BuildStockpileTask.new('fd_seeds2', ['fd_dig_-2'], [12, 8, -2], 1, 3, 'food_seeds')
# $tasks['cl_seeds2'] = BuildStockpileTask.new('cl_seeds2', ['cl_dig_-2'], [35, 8, -2], 1, 3, 'None')
# $tasks['dr_still1'] = BuildTask.new('dr_still1', ['dr_dig_-3'], [1, 1, -3], :Workshop, :Still, [])
# $tasks['dr_brewable'] = BuildStockpileTask.new('dr_brewable', ['dr_dig_-3'], [4, 1, -3], 7, 10, 'dr_brewable')
# $tasks['fd_millable'] = BuildStockpileTask.new('fd_millable', ['fd_dig_-3'], [12, 1, -3], 8, 3, 'fd_millable')
# $tasks['fd_bags'] = BuildStockpileTask.new('fd_bags', ['fd_dig_-3'], [20, 1, -3], 2, 2, 'bags')
# $tasks['cl_bags'] = BuildStockpileTask.new('cl_bags', ['cl_dig_-3'], [26, 1, -3], 1, 4, 'bags')
# $tasks['cl_millable'] = BuildStockpileTask.new('cl_millable', ['cl_dig_-3'], [27, 1, -3], 6, 5, 'None')
# $tasks['cl_loom'] = BuildTask.new('cl_loom', ['cl_dig_-3'], [33, 1, -3], :Workshop, :Loom, [])
# $tasks['dr_pots1'] = BuildStockpileTask.new('dr_pots1', ['dr_dig_-3'], [2, 4, -3], 2, 4, 'pots')
# $tasks['fd_cookable'] = BuildStockpileTask.new('fd_cookable', ['fd_dig_-3'], [13, 4, -3], 9, 4, 'food_cookable')
# $tasks['cl_thread'] = BuildStockpileTask.new('cl_thread', ['cl_dig_-3'], [33, 4, -3], 2, 4, 'None')
# $tasks['cl_processable'] = BuildStockpileTask.new('cl_processable', ['cl_dig_-3'], [26, 6, -3], 7, 5, 'None')
# $tasks['dr_still2'] = BuildTask.new('dr_still2', ['dr_dig_-3'], [1, 8, -3], :Workshop, :Still, [])
# $tasks['fd_processable'] = BuildStockpileTask.new('fd_processable', ['fd_dig_-3'], [12, 8, -3], 7, 3, 'fd_processable')
# $tasks['fd_farmers'] = BuildTask.new('fd_farmers', ['fd_dig_-3'], [19, 8, -3], :Workshop, :Farmers, [])
# $tasks['cl_farmers'] = BuildTask.new('cl_farmers', ['cl_dig_-3'], [33, 8, -3], :Workshop, :Farmers, [])
# $tasks['le_tanner'] = BuildTask.new('le_tanner', ['le_dig_-3'], [1, 12, -3], :Workshop, :Tanners, [])
# $tasks['le_hide'] = BuildStockpileTask.new('le_hide', ['le_dig_-3'], [4, 12, -3], 7, 3, 'hide')
# $tasks['pa_butcher_out'] = BuildStockpileTask.new('pa_butcher_out', ['pa_dig_-3'], [12, 12, -3], 3, 7, 'butcher_out')
# $tasks['pa_buckets'] = BuildStockpileTask.new('pa_buckets', ['pa_dig_-3'], [18, 12, -3], 1, 2, 'buckets')
# $tasks['pa_milker'] = BuildTask.new('pa_milker', ['pa_dig_-3'], [19, 12, -3], :Workshop, :Farmers, [])
# $tasks['so_soap'] = BuildStockpileTask.new('so_soap', ['so_dig_-3'], [26, 12, -3], 1, 3, 'soap')
# $tasks['so_soapmaker'] = BuildTask.new('so_soapmaker', ['so_dig_-3'], [27, 12, -3], :Workshop, :Custom, [])
# $tasks['so_tallow'] = BuildStockpileTask.new('so_tallow', ['so_dig_-3'], [30, 12, -3], 3, 4, 'tallow')
# $tasks['so_buckets'] = BuildStockpileTask.new('so_buckets', ['so_dig_-3'], [33, 12, -3], 3, 2, 'buckets')
# $tasks['bo_bones'] = BuildStockpileTask.new('bo_bones', ['bo_dig_-3'], [37, 12, -3], 10, 4, 'bones')
# $tasks['so_lye'] = BuildStockpileTask.new('so_lye', ['so_dig_-3'], [33, 14, -3], 3, 1, 'lye')
# $tasks['le_leatherworker'] = BuildTask.new('le_leatherworker', ['le_dig_-3'], [1, 15, -3], :Workshop, :Leatherworks, [])
# $tasks['le_leather'] = BuildStockpileTask.new('le_leather', ['le_dig_-3'], [4, 15, -3], 7, 3, 'leather')
# $tasks['pa_yarn'] = BuildStockpileTask.new('pa_yarn', ['pa_dig_-3'], [19, 15, -3], 3, 4, 'None')
# $tasks['so_fat'] = BuildStockpileTask.new('so_fat', ['so_dig_-3'], [26, 15, -3], 4, 4, 'None')
# $tasks['so_ashery'] = BuildTask.new('so_ashery', ['so_dig_-3'], [33, 15, -3], :Workshop, :Ashery, [{:JobType => :MakePotashFromAsh},{:JobType => :MakeLye}])
# $tasks['so_kitchen'] = BuildTask.new('so_kitchen', ['so_dig_-3'], [30, 16, -3], :Workshop, :Kitchen, [])
# $tasks['bo_bowyer_out'] = BuildStockpileTask.new('bo_bowyer_out', ['bo_dig_-3'], [37, 16, -3], 7, 3, 'crossbows')
# $tasks['bo_bowyer'] = BuildTask.new('bo_bowyer', ['bo_dig_-3'], [44, 16, -3], :Workshop, :Bowyers, [{:JobType => :MakeAmmo}])
# $tasks['le_leatherworker_out'] = BuildStockpileTask.new('le_leatherworker_out', ['le_dig_-3'], [1, 18, -3], 10, 4, 'None')
# $tasks['so_ash'] = BuildStockpileTask.new('so_ash', ['so_dig_-3'], [33, 18, -3], 3, 1, 'ash')
# $tasks['pa_butcher'] = BuildTask.new('pa_butcher', ['pa_dig_-3'], [12, 19, -3], :Workshop, :Butchers, [])
# $tasks['pa_shearer'] = BuildTask.new('pa_shearer', ['pa_dig_-3'], [19, 19, -3], :Workshop, :Farmers, [])
# $tasks['so_potash'] = BuildStockpileTask.new('so_potash', ['so_dig_-3'], [26, 19, -3], 7, 3, 'potash')
# $tasks['so_furnace'] = BuildTask.new('so_furnace', ['so_dig_-3'], [33, 19, -3], :Furnace, :WoodFurnace, [{:JobType => :MakeAsh, :ItemType => 22319}])
# $tasks['bo_crafts_out'] = BuildStockpileTask.new('bo_crafts_out', ['bo_dig_-3'], [37, 19, -3], 7, 3, 'bolts')
# $tasks['bo_crafter'] = BuildTask.new('bo_crafter', ['bo_dig_-3'], [44, 19, -3], :Workshop, :Craftsdwarfs, [{:JobType => :MakeWeapon}])
# $tasks['st_mechanic_out'] = BuildStockpileTask.new('st_mechanic_out', ['st_dig_-3'], [1, 26, -3], 3, 4, 'st_mechanics_out')
# $tasks['st_mason_out'] = BuildStockpileTask.new('st_mason_out', ['st_dig_-3'], [4, 26, -3], 4, 10, 'None')
# $tasks['st_crafts_out'] = BuildStockpileTask.new('st_crafts_out', ['st_dig_-3'], [8, 26, -3], 3, 4, 'None')
# $tasks['wo_carpenter'] = BuildTask.new('wo_carpenter', ['wo_dig_-3'], [12, 26, -3], :Workshop, :Carpenters, [{:JobType => :MakeBucket},{:JobType => :MakeCage},{:JobType => :ConstructBed},{:JobType => :ConstructSplint},{:JobType => :ConstructCrutch}])
# $tasks['wo_carpenter_out'] = BuildStockpileTask.new('wo_carpenter_out', ['wo_dig_-3'], [15, 26, -3], 7, 3, 'wo_carpenter_out')
# $tasks['wo_wood'] = BuildStockpileTask.new('wo_wood', ['wo_dig_-3'], [26, 26, -3], 10, 10, 'wood')
# $tasks['mt_flux'] = BuildStockpileTask.new('mt_flux', ['mt_dig_-3'], [37, 26, -3], 4, 10, 'flux')
# $tasks['mt_ore'] = BuildStockpileTask.new('mt_ore', ['mt_dig_-3'], [41, 26, -3], 4, 10, 'ore')
# $tasks['mt_smeltable'] = BuildStockpileTask.new('mt_smeltable', ['mt_dig_-3'], [45, 26, -3], 2, 10, 'None')
# $tasks['wo_crafts'] = BuildTask.new('wo_crafts', ['wo_dig_-3'], [12, 29, -3], :Workshop, :Craftsdwarfs, [])
# $tasks['wo_crafts_out'] = BuildStockpileTask.new('wo_crafts_out', ['wo_dig_-3'], [15, 29, -3], 7, 2, 'None')
# $tasks['st_mech'] = BuildTask.new('st_mech', ['st_dig_-3'], [1, 30, -3], :Workshop, :Mechanics, [{:JobType => :ConstructMechanisms}])
# $tasks['st_crafts'] = BuildTask.new('st_crafts', ['st_dig_-3'], [8, 30, -3], :Workshop, :Craftsdwarfs, [])
# $tasks['wo_arrowheads'] = BuildStockpileTask.new('wo_arrowheads', ['wo_dig_-3'], [15, 31, -3], 2, 5, 'wo_arrowheads')
# $tasks['wo_siege'] = BuildTask.new('wo_siege', ['wo_dig_-3'], [17, 31, -3], :Workshop, :Siege, [])
# $tasks['wo_siege_out'] = BuildStockpileTask.new('wo_siege_out', ['wo_dig_-3'], [12, 32, -3], 3, 4, 'None')
# $tasks['st_mason1'] = BuildTask.new('st_mason1', ['st_dig_-3'], [1, 33, -3], :Workshop, :Masons, [{:JobType => :ConstructBlocks},{:JobType => :ConstructCoffin},{:JobType => :ConstructSlab},{:JobType => :MakeArmorStand},{:JobType => :MakeWeaponRack}])
# $tasks['st_mason2'] = BuildTask.new('st_mason2', ['st_dig_-3'], [8, 33, -3], :Workshop, :Masons, [{:JobType => :ConstructBlocks},{:JobType => :ConstructCoffin},{:JobType => :ConstructSlab},{:JobType => :MakeArmorStand},{:JobType => :MakeWeaponRack}])
# $tasks['st_stone'] = BuildStockpileTask.new('st_stone', ['st_dig_-3'], [1, 37, -3], 10, 10, 'stone')
# $tasks['gl_glassmaker1'] = BuildTask.new('gl_glassmaker1', ['gl_dig_-3'], [12, 37, -3], :Furnace, :GlassFurnace, [{:JobType => :CollectSand}])
# $tasks['gl_glassmaker2'] = BuildTask.new('gl_glassmaker2', ['gl_dig_-3'], [15, 37, -3], :Furnace, :GlassFurnace, [{:JobType => :CollectSand}])
# $tasks['gl_out'] = BuildStockpileTask.new('gl_out', ['gl_dig_-3'], [18, 37, -3], 4, 10, 'None')
# $tasks['ch_furnace1'] = BuildTask.new('ch_furnace1', ['ch_dig_-3'], [27, 37, -3], :Furnace, :WoodFurnace, [{:JobType => :MakeCharcoal}])
# $tasks['ch_furnace2'] = BuildTask.new('ch_furnace2', ['ch_dig_-3'], [30, 37, -3], :Furnace, :WoodFurnace, [{:JobType => :MakeCharcoal}])
# $tasks['ch_furnace3'] = BuildTask.new('ch_furnace3', ['ch_dig_-3'], [33, 37, -3], :Furnace, :WoodFurnace, [{:JobType => :MakeCharcoal}])
# $tasks['mt_smelt1'] = BuildTask.new('mt_smelt1', ['mt_dig_-3'], [38, 37, -3], :Furnace, :Smelter, [])
# $tasks['mt_smelt2'] = BuildTask.new('mt_smelt2', ['mt_dig_-3'], [41, 37, -3], :Furnace, :Smelter, [])
# $tasks['mt_smelt3'] = BuildTask.new('mt_smelt3', ['mt_dig_-3'], [44, 37, -3], :Furnace, :Smelter, [])
# $tasks['gl_bags'] = BuildStockpileTask.new('gl_bags', ['gl_dig_-3'], [13, 40, -3], 1, 4, 'bags')
# $tasks['gl_sand'] = BuildStockpileTask.new('gl_sand', ['gl_dig_-3'], [14, 40, -3], 4, 4, 'sand')
# $tasks['ch_charcoal'] = BuildStockpileTask.new('ch_charcoal', ['ch_dig_-3'], [27, 40, -3], 9, 7, 'charcoal')
# $tasks['mt_pigiron'] = BuildStockpileTask.new('mt_pigiron', ['mt_dig_-3'], [41, 40, -3], 3, 4, 'bars_pig_iron')
# $tasks['mt_iron'] = BuildStockpileTask.new('mt_iron', ['mt_dig_-3'], [44, 40, -3], 3, 4, 'bars_iron')
# $tasks['gl_glassmaker3'] = BuildTask.new('gl_glassmaker3', ['gl_dig_-3'], [12, 44, -3], :Furnace, :GlassFurnace, [])
# $tasks['gl_glassmaker4'] = BuildTask.new('gl_glassmaker4', ['gl_dig_-3'], [15, 44, -3], :Furnace, :GlassFurnace, [])
# $tasks['mt_smelt4'] = BuildTask.new('mt_smelt4', ['mt_dig_-3'], [38, 44, -3], :Furnace, :Smelter, [])
# $tasks['mt_smelt5'] = BuildTask.new('mt_smelt5', ['mt_dig_-3'], [41, 44, -3], :Furnace, :Smelter, [])
# $tasks['mt_smelt6'] = BuildTask.new('mt_smelt6', ['mt_dig_-3'], [44, 44, -3], :Furnace, :Smelter, [])
# $tasks['dr_still3'] = BuildTask.new('dr_still3', ['dr_dig_-4'], [1, 1, -4], :Workshop, :Still, [])
# $tasks['dr_out'] = BuildStockpileTask.new('dr_out', ['dr_dig_-4'], [4, 1, -4], 7, 10, 'drinks')
# $tasks['fd_kitchen1'] = BuildTask.new('fd_kitchen1', ['fd_dig_-4'], [12, 1, -4], :Workshop, :Kitchen, [{:JobType => :PrepareMeal}])
# $tasks['fd_out'] = BuildStockpileTask.new('fd_out', ['fd_dig_-4'], [15, 1, -4], 7, 10, 'prepared_meals')
# $tasks['cl_dye'] = BuildStockpileTask.new('cl_dye', ['cl_dig_-4'], [26, 1, -4], 3, 3, 'None')
# $tasks['cl_dyer'] = BuildTask.new('cl_dyer', ['cl_dig_-4'], [29, 1, -4], :Workshop, :Dyers, [])
# $tasks['cl_cloth'] = BuildStockpileTask.new('cl_cloth', ['cl_dig_-4'], [32, 1, -4], 4, 3, 'None')
# $tasks['dr_pots2'] = BuildStockpileTask.new('dr_pots2', ['dr_dig_-4'], [2, 4, -4], 2, 4, 'pots')
# $tasks['fd_pots'] = BuildStockpileTask.new('fd_pots', ['fd_dig_-4'], [13, 4, -4], 2, 4, 'pots')
# $tasks['cl_clothier'] = BuildTask.new('cl_clothier', ['cl_dig_-4'], [26, 4, -4], :Workshop, :Clothiers, [])
# $tasks['cl_dyedcloth'] = BuildStockpileTask.new('cl_dyedcloth', ['cl_dig_-4'], [29, 4, -4], 6, 3, 'None')
# $tasks['cl_out'] = BuildStockpileTask.new('cl_out', ['cl_dig_-4'], [26, 7, -4], 9, 4, 'None')
# $tasks['dr_still4'] = BuildTask.new('dr_still4', ['dr_dig_-4'], [1, 8, -4], :Workshop, :Still, [])
# $tasks['fd_kitchen2'] = BuildTask.new('fd_kitchen2', ['fd_dig_-4'], [12, 8, -4], :Workshop, :Kitchen, [{:JobType => :PrepareMeal}])
# $tasks['gm_cut'] = BuildStockpileTask.new('gm_cut', ['gm_dig_-4'], [1, 37, -4], 10, 5, 'gem_rough')
# $tasks['mt_forge1'] = BuildTask.new('mt_forge1', ['mt_dig_-4'], [26, 37, -4], :Workshop, :MetalsmithsForge, [])
# $tasks['mt_out'] = BuildStockpileTask.new('mt_out', ['mt_dig_-4'], [29, 37, -4], 4, 10, 'None')
# $tasks['mt_forge2'] = BuildTask.new('mt_forge2', ['mt_dig_-4'], [33, 37, -4], :Workshop, :MetalsmithsForge, [])
# $tasks['mt_bars'] = BuildStockpileTask.new('mt_bars', ['mt_dig_-4'], [38, 37, -4], 9, 10, 'bars')
# $tasks['gm_uncut'] = BuildStockpileTask.new('gm_uncut', ['gm_dig_-4'], [1, 42, -4], 10, 5, 'gem_cut')
# $tasks['mt_forge3'] = BuildTask.new('mt_forge3', ['mt_dig_-4'], [26, 44, -4], :Workshop, :MetalsmithsForge, [])
# $tasks['mt_forge4'] = BuildTask.new('mt_forge4', ['mt_dig_-4'], [33, 44, -4], :Workshop, :MetalsmithsForge, [])
