$z_pasture = -2
$z_industry = -3
$z_entrance = -4
$z_dining = -5
$z_accoma = -6
$z_accomb = -7
$z_blanka = -8
$z_blankb = -9
$z_caverns = -10

addTask(DigTask.new("dig_surface_1", [], [0, 0, 0], "surface.csv", 1))
addTask(DigTask.new("dig_surface_2", [], [0, 0, 0], "surface.csv", 2))
addTask(DigTask.new("dig_surface_3", ["fg_in","dig_industry_3","dig_industry_9","dig_entrance_2"], [0, 0, 0], "surface.csv", 3))


addTask(DigTask.new("dig_water_1", ["dig_surface_1"], [0, 0, -1], "water.csv", 1))
addTask(DigTask.new("dig_water_2", ["dig_surface_2"], [0, 0, -1], "water.csv", 2))


addTask(BuildCivZoneTask.new('temp_meeting', ['dig_pasture_1'], [22, 1, -2], 1, 1, :MeetingArea, nil))
addTask(BuildStockpileTask.new('lostandfound', ['dig_pasture_2'], [32, 1, -2], 1, 1, 'wood', false, false))
addTask(BuildTask.new('pcagetrap1', ['dig_pasture_5'], [8, 2, -2], :Trap, :CageTrap, nil))
addTask(BuildTask.new('pcagetrap2', ['dig_pasture_5'], [9, 2, -2], :Trap, :CageTrap, nil))
addTask(BuildTask.new('pcagetrap3', ['dig_pasture_5'], [10, 2, -2], :Trap, :CageTrap, nil))
addTask(BuildTask.new('pcagetrap4', ['dig_pasture_5'], [11, 2, -2], :Trap, :CageTrap, nil))
addTask(BuildFarmTask.new('farm1', ['dig_pasture_9'], [22, 6, -2], 1, 1, [174,174,174,174]))
addTask(BuildFarmTask.new('farm2', ['dig_pasture_9'], [25, 6, -2], 1, 1, [176,176,176,176]))
addTask(BuildFarmTask.new('farm3', ['dig_pasture_3'], [28, 6, -2], 1, 1, [172,172,172,172]))
addTask(BuildCivZoneTask.new('fishingzone', ['dig_pasture_7'], [4, 9, -2], 1, 1, :FishAndDrink, nil))
addTask(BuildFarmTask.new('farm4', ['dig_pasture_9'], [22, 9, -2], 1, 1, [175,175,175,175]))
addTask(BuildFarmTask.new('farm5', ['dig_pasture_9'], [25, 9, -2], 1, 1, [187,187,187,187]))
addTask(BuildFarmTask.new('farm6', ['dig_pasture_9'], [28, 9, -2], 1, 1, [173,173,173,173]))
addTask(BuildCivZoneTask.new('pasture1', ['dig_pasture_4'], [31, 9, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture2', ['dig_pasture_4'], [35, 9, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture3', ['dig_pasture_4'], [39, 9, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture4', ['dig_pasture_4'], [43, 9, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture5', ['dig_pasture_4'], [31, 13, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture6', ['dig_pasture_4'], [35, 13, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture7', ['dig_pasture_4'], [39, 13, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture8', ['dig_pasture_4'], [43, 13, -2], 1, 1, :Pasture, 165))
addTask(BuildTask.new('nestbox1', ['dig_pasture_4'], [35, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox1_pasture', ['dig_pasture_4'], [35, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox2', ['dig_pasture_4'], [36, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox2_pasture', ['dig_pasture_4'], [36, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox3', ['dig_pasture_4'], [37, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox3_pasture', ['dig_pasture_4'], [37, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox4', ['dig_pasture_4'], [38, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox4_pasture', ['dig_pasture_4'], [38, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox5', ['dig_pasture_4'], [39, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox5_pasture', ['dig_pasture_4'], [39, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox6', ['dig_pasture_4'], [40, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox6_pasture', ['dig_pasture_4'], [40, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox7', ['dig_pasture_4'], [41, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox7_pasture', ['dig_pasture_4'], [41, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox8', ['dig_pasture_4'], [42, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox8_pasture', ['dig_pasture_4'], [42, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox9', ['dig_pasture_4'], [43, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox9_pasture', ['dig_pasture_4'], [43, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox10', ['dig_pasture_4'], [44, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox10_pasture', ['dig_pasture_4'], [44, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox11', ['dig_pasture_4'], [45, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox11_pasture', ['dig_pasture_4'], [45, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildTask.new('nestbox12', ['dig_pasture_4'], [46, 17, -2], :NestBox, nil, nil))
addTask(BuildCivZoneTask.new('nestbox12_pasture', ['dig_pasture_4'], [46, 17, -2], 1, 1, :Pasture, 177))
addTask(BuildCivZoneTask.new('pasture9', ['dig_pasture_4'], [31, 18, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture10', ['dig_pasture_4'], [35, 18, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture11', ['dig_pasture_4'], [39, 18, -2], 1, 1, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture12', ['dig_pasture_4'], [43, 18, -2], 1, 1, :Pasture, 165))
addTask(BuildTask.new('fg_in', ['dig_pasture_7'], [1, 46, -2], :GrateFloor, nil, nil))
addTask(DigTask.new("dig_pasture_1", ["dig_water_1"], [0, 0, -2], "pasture.csv", 1))
addTask(DigTask.new("dig_pasture_2", ["dig_pasture_1"], [0, 0, -2], "pasture.csv", 2))
addTask(DigTask.new("dig_pasture_3", ["dig_pasture_2"], [0, 0, -2], "pasture.csv", 3))
addTask(DigTask.new("dig_pasture_4", ["dig_pasture_3"], [0, 0, -2], "pasture.csv", 4))
addTask(DigTask.new("dig_pasture_5", ["dig_pasture_4"], [0, 0, -2], "pasture.csv", 5))
addTask(DigTask.new("dig_pasture_6", ["dig_pasture_5"], [0, 0, -2], "pasture.csv", 6))
addTask(DigTask.new("dig_pasture_7", ["dig_pasture_1"], [0, 0, -2], "pasture.csv", 7))
addTask(DigTask.new("dig_pasture_8", ["dig_water_2"], [0, 0, -2], "pasture.csv", 8))
addTask(DigTask.new("dig_pasture_9", ["dig_pasture_1"], [0, 0, -2], "pasture.csv", 9))
addTask(BuildCivZoneTask.new('temp_meeting', ['dig_pasture_1'], [22, 1, -2], 10, 5, :MeetingArea, nil))
addTask(BuildStockpileTask.new('lostandfound', ['dig_pasture_2'], [32, 1, -2], 15, 8, 'wood', false, false))
addTask(BuildFarmTask.new('farm1', ['dig_pasture_9'], [22, 6, -2], 3, 3, [174,174,174,174]))
addTask(BuildFarmTask.new('farm2', ['dig_pasture_9'], [25, 6, -2], 3, 3, [176,176,176,176]))
addTask(BuildFarmTask.new('farm3', ['dig_pasture_3'], [28, 6, -2], 3, 3, [172,172,172,172]))
addTask(BuildCivZoneTask.new('fishingzone', ['dig_pasture_7'], [4, 9, -2], 1, 31, :FishAndDrink, nil))
addTask(BuildFarmTask.new('farm4', ['dig_pasture_9'], [22, 9, -2], 3, 3, [175,175,175,175]))
addTask(BuildFarmTask.new('farm5', ['dig_pasture_9'], [25, 9, -2], 3, 3, [187,187,187,187]))
addTask(BuildFarmTask.new('farm6', ['dig_pasture_9'], [28, 9, -2], 3, 3, [173,173,173,173]))
addTask(BuildCivZoneTask.new('pasture1', ['dig_pasture_4'], [31, 9, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture2', ['dig_pasture_4'], [35, 9, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture3', ['dig_pasture_4'], [39, 9, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture4', ['dig_pasture_4'], [43, 9, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture5', ['dig_pasture_4'], [31, 13, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture6', ['dig_pasture_4'], [35, 13, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture7', ['dig_pasture_4'], [39, 13, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture8', ['dig_pasture_4'], [43, 13, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture9', ['dig_pasture_4'], [31, 18, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture10', ['dig_pasture_4'], [35, 18, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture11', ['dig_pasture_4'], [39, 18, -2], 4, 4, :Pasture, 165))
addTask(BuildCivZoneTask.new('pasture12', ['dig_pasture_4'], [43, 18, -2], 4, 4, :Pasture, 165))


addTask(BuildStockpileTask.new('dyedthread', ['dig_industry_10'], [34, 7, -3], 1, 1, 'dyethread', false, true))
addTask(BuildStockpileTask.new('cloth', ['dig_industry_10'], [37, 7, -3], 1, 1, 'dyecloth', false, true))
addTask(BuildTask.new('clothiers', ['dig_industry_10'], [40, 7, -3], :Workshop, :Clothiers, nil))
addTask(BuildStockpileTask.new('cl_decoratable', ['dig_industry_10'], [43, 7, -3], 1, 1, 'cl_decoratable', false, false))
addTask(BuildTask.new('millstone', ['dig_industry_10'], [32, 8, -3], :Workshop, :Millstone, [{:JobType => :MillPlants}]))
addTask(BuildTask.new('dyers', ['dig_industry_10'], [34, 8, -3], :Workshop, :Dyers, nil))
addTask(BuildTask.new('ashfurnace', ['dig_industry_10'], [23, 9, -3], :Furnace, :WoodFurnace, [{:JobType => :MakeAsh}]))
addTask(BuildStockpileTask.new('meals_drinks', ['dig_industry_2'], [26, 9, -3], 1, 1, 'mealsdrinks', true, false))
addTask(BuildTask.new('still1', ['dig_industry_2'], [28, 9, -3], :Workshop, :Still, [{:JobType => 211}]))
addTask(BuildStockpileTask.new('food', ['dig_industry_2'], [31, 9, -3], 1, 1, 'food', true, false))
addTask(BuildTask.new('loom', ['dig_industry_10'], [37, 9, -3], :Workshop, :Loom, [{:JobType => :WeaveCloth}]))
addTask(BuildTask.new('leatherworks', ['dig_industry_10'], [40, 10, -3], :Workshop, :Leatherworks, [{:JobType => :ConstructChest},{:JobType => :MakeFlask},{:JobType => :MakeQuiver},{:JobType => :MakeBackpack}]))
addTask(BuildStockpileTask.new('thread', ['dig_industry_10'], [34, 11, -3], 1, 1, 'thread', false, true))
addTask(BuildStockpileTask.new('ash', ['dig_industry_10'], [23, 12, -3], 1, 1, 'ash', false, false))
addTask(BuildTask.new('still2', ['dig_industry_10'], [28, 12, -3], :Workshop, :Still, [{:JobType => 211}]))
addTask(BuildStockpileTask.new('dye', ['dig_industry_10'], [34, 12, -3], 1, 1, 'dye', false, false))
addTask(BuildStockpileTask.new('leather', ['dig_industry_10'], [37, 12, -3], 1, 1, 'leather', false, true))
addTask(BuildStockpileTask.new('potash', ['dig_industry_10'], [21, 13, -3], 1, 1, 'potash', false, true))
addTask(BuildTask.new('ashery', ['dig_industry_10'], [23, 13, -3], :Workshop, :Ashery, [{:JobType => :MakePotashFromAsh},{:JobType => :MakeLye}]))
addTask(BuildTask.new('farmers', ['dig_industry_2'], [34, 13, -3], :Workshop, :Farmers, [{:JobType => :MilkCreature},{:JobType => :MakeCheese},{:JobType => 211},{:JobType => :ProcessPlants}]))
addTask(BuildTask.new('tanners', ['dig_industry_10'], [37, 14, -3], :Workshop, :Tanners, nil))
addTask(BuildTask.new('kitchen1', ['dig_industry_2'], [28, 15, -3], :Workshop, :Kitchen, [{:JobType => :PrepareMeal},{:JobType => 211}]))
addTask(BuildTask.new('boltcrafters', ['dig_industry_10'], [40, 15, -3], :Workshop, :Craftsdwarfs, [{:JobType => :MakeAmmo}]))
addTask(BuildStockpileTask.new('crossbow_goods', ['dig_industry_10'], [43, 15, -3], 1, 1, 'crossbow_goods', false, true))
addTask(BuildStockpileTask.new('lye', ['dig_industry_10'], [23, 16, -3], 1, 1, 'lye', false, false))
addTask(BuildStockpileTask.new('bags1', ['dig_industry_2'], [34, 16, -3], 1, 1, 'bags', false, false))
addTask(BuildTask.new('soapmaker', ['dig_industry_10'], [23, 17, -3], :Workshop, :Custom, [{:JobType => 211}]))
addTask(BuildStockpileTask.new('buckets', ['dig_industry_2'], [35, 17, -3], 1, 1, 'buckets', false, false))
addTask(BuildStockpileTask.new('hide', ['dig_industry_10'], [37, 17, -3], 1, 1, 'hide', false, false))
addTask(BuildTask.new('kitchen2', ['dig_industry_10'], [28, 18, -3], :Workshop, :Kitchen, [{:JobType => :PrepareMeal},{:JobType => 211}]))
addTask(BuildTask.new('butchers', ['dig_industry_2'], [34, 18, -3], :Workshop, :Butchers, nil))
addTask(BuildStockpileTask.new('wood_or_bone', ['dig_industry_10'], [37, 18, -3], 1, 1, 'bone', false, true))
addTask(BuildTask.new('bowyers', ['dig_industry_10'], [40, 18, -3], :Workshop, :Bowyers, [{:JobType => :MakeWeapon, :ItemSubType => 6}]))
addTask(BuildStockpileTask.new('soap', ['dig_industry_10'], [23, 20, -3], 1, 1, 'soap', false, true))
addTask(BuildStockpileTask.new('hoof_etc', ['dig_industry_1'], [34, 22, -3], 1, 1, 'hoofetc', false, false))
addTask(BuildStockpileTask.new('mechanisms', ['dig_industry_1'], [37, 22, -3], 1, 1, 'mechanics_out', false, false))
addTask(BuildStockpileTask.new('stone', ['dig_industry_1'], [43, 22, -3], 1, 1, 'stone', false, false))
addTask(BuildStockpileTask.new('bars', ['dig_industry_11'], [26, 24, -3], 1, 1, 'bars', false, false))
addTask(BuildTask.new('forge1', ['dig_industry_11'], [28, 24, -3], :Workshop, :MetalsmithsForge, nil))
addTask(BuildTask.new('carpenters', ['dig_industry_1'], [31, 24, -3], :Workshop, :Carpenters, [{:JobType => :MakeBucket},{:JobType => :ConstructBin},{:JobType => :MakeCage},{:JobType => :ConstructBed},{:JobType => :ConstructSplint},{:JobType => :ConstructCrutch}]))
addTask(BuildTask.new('bonecrafters', ['dig_industry_10'], [34, 24, -3], :Workshop, :Craftsdwarfs, nil))
addTask(BuildTask.new('mechanics', ['dig_industry_1'], [37, 24, -3], :Workshop, :Mechanics, [{:JobType => :ConstructMechanisms}]))
addTask(BuildTask.new('stonecrafters1', ['dig_industry_1'], [40, 24, -3], :Workshop, :Craftsdwarfs, [{:JobType => 218, :ItemSubType => 12},{:JobType => :MakeGoblet}, {:JobType => :MakeCrafts}]))
addTask(BuildStockpileTask.new('ore', ['dig_industry_11'], [19, 27, -3], 1, 1, 'ore', false, false))
addTask(BuildStockpileTask.new('flux', ['dig_industry_11'], [21, 27, -3], 1, 1, 'flux', false, false))
addTask(BuildTask.new('smelter1', ['dig_industry_11'], [23, 27, -3], :Furnace, :Smelter, nil))
addTask(BuildTask.new('forge2', ['dig_industry_11'], [28, 27, -3], :Workshop, :MetalsmithsForge, nil))
addTask(BuildStockpileTask.new('undecoratable', ['dig_industry_11'], [31, 27, -3], 1, 1, 'undecoratable', false, false))
addTask(BuildStockpileTask.new('decoratable', ['dig_industry_11'], [33, 27, -3], 1, 1, 'decoratable', false, false))
addTask(BuildTask.new('stonecrafters2', ['dig_industry_1'], [40, 27, -3], :Workshop, :Craftsdwarfs, [{:JobType => 218, :ItemSubType => 12},{:JobType => 218, :ItemSubType => 10}, {:JobType => :MakeCrafts}]))
addTask(BuildTask.new('smelter2', ['dig_industry_11'], [23, 30, -3], :Furnace, :Smelter, nil))
addTask(BuildTask.new('forge3', ['dig_industry_11'], [28, 30, -3], :Workshop, :MetalsmithsForge, nil))
addTask(BuildTask.new('masons1', ['dig_industry_10'], [40, 30, -3], :Workshop, :Masons, [{:JobType => :ConstructMillstone}, {:JobType => :ConstructCabinet}, {:JobType => :ConstructTable}, {:JobType => :ConstructSlab}, {:JobType => :ConstructWeaponRack}]))
addTask(BuildTask.new('smelter3', ['dig_industry_11'], [23, 33, -3], :Furnace, :Smelter, nil))
addTask(BuildTask.new('forge4', ['dig_industry_11'], [28, 33, -3], :Workshop, :MetalsmithsForge, nil))
addTask(BuildTask.new('kiln', ['dig_industry_11'], [31, 33, -3], :Furnace, :Kiln, nil))
addTask(BuildTask.new('glassfurnace1', ['dig_industry_11'], [34, 33, -3], :Furnace, :GlassFurnace, nil))
addTask(BuildTask.new('jewelsetters', ['dig_industry_11'], [37, 33, -3], :Workshop, :Jewelers, nil))
addTask(BuildTask.new('masons2', ['dig_industry_10'], [40, 33, -3], :Workshop, :Masons, [{:JobType => :ConstructDoor}, {:JobType => :ConstructBlocks}, {:JobType => :ConstructChest}, {:JobType => :ConstructThrone}, {:JobType => :ConstructCoffin}, {:JobType => :ConstructArmorStand}]))
addTask(BuildStockpileTask.new('ballista_arrowheads', ['dig_industry_11'], [25, 36, -3], 1, 1, 'ballista_arrowheads', false, false))
addTask(BuildStockpileTask.new('fuel', ['dig_industry_11'], [28, 36, -3], 1, 1, 'fuel', false, false))
addTask(BuildStockpileTask.new('clay', ['dig_industry_11'], [31, 36, -3], 1, 1, 'clay', false, false))
addTask(BuildStockpileTask.new('raw_glass', ['dig_industry_11'], [34, 36, -3], 1, 1, 'raw_glass', false, false))
addTask(BuildStockpileTask.new('cut_gems', ['dig_industry_11'], [37, 36, -3], 1, 1, 'gem_cut', false, false))
addTask(BuildStockpileTask.new('siege_goods', ['dig_industry_11'], [21, 37, -3], 1, 1, 'siege_out', false, false))
addTask(BuildTask.new('siege', ['dig_industry_11'], [23, 37, -3], :Workshop, :Siege, nil))
addTask(BuildTask.new('glassfurnace2', ['dig_industry_11'], [34, 37, -3], :Furnace, :GlassFurnace, nil))
addTask(BuildStockpileTask.new('pearlash', ['dig_industry_11'], [31, 38, -3], 1, 1, 'pearlash', false, false))
addTask(BuildTask.new('jewelcutters', ['dig_industry_11'], [37, 38, -3], :Workshop, :Jewelers, nil))
addTask(BuildStockpileTask.new('rough_gems', ['dig_industry_11'], [40, 38, -3], 1, 1, 'gem_rough', false, false))
addTask(BuildTask.new('fuelfurnace1', ['dig_industry_11'], [28, 39, -3], :Furnace, :WoodFurnace, nil))
addTask(BuildTask.new('fuelfurnace2', ['dig_industry_11'], [31, 39, -3], :Furnace, :WoodFurnace, nil))
addTask(BuildStockpileTask.new('bags2', ['dig_industry_11'], [34, 40, -3], 1, 1, 'bags', false, false))
addTask(BuildStockpileTask.new('sand', ['dig_industry_11'], [34, 41, -3], 1, 1, 'sand', false, false))
addTask(DigTask.new("dig_industry_1", ["dig_pasture_6"], [0, 0, -3], "industry.csv", 1))
addTask(DigTask.new("dig_industry_2", ["dig_industry_1"], [0, 0, -3], "industry.csv", 2))
addTask(DigTask.new("dig_industry_3", ["dig_pasture_7"], [0, 0, -3], "industry.csv", 3))
addTask(DigTask.new("dig_industry_4", ["dig_industry_3"], [0, 0, -3], "industry.csv", 4))
addTask(DigTask.new("dig_industry_5", ["dig_industry_4"], [0, 0, -3], "industry.csv", 5))
addTask(DigTask.new("dig_industry_6", ["dig_industry_5"], [0, 0, -3], "industry.csv", 6))
addTask(DigTask.new("dig_industry_7", ["dig_industry_6"], [0, 0, -3], "industry.csv", 7))
addTask(DigTask.new("dig_industry_8", ["dig_industry_6"], [0, 0, -3], "industry.csv", 8))
addTask(DigTask.new("dig_industry_9", ["dig_pasture_8"], [0, 0, -3], "industry.csv", 9))
addTask(DigTask.new("dig_industry_10", ["dig_industry_1"], [0, 0, -3], "industry.csv", 10))
addTask(DigTask.new("dig_industry_11", ["dig_industry_1"], [0, 0, -3], "industry.csv", 11))
addTask(BuildStockpileTask.new('dyedthread', ['dig_industry_10'], [34, 7, -3], 3, 1, 'dyethread', false, true))
addTask(BuildStockpileTask.new('cloth', ['dig_industry_10'], [37, 7, -3], 3, 2, 'dyecloth', false, true))
addTask(BuildTask.new('clothiers', ['dig_industry_10'], [40, 7, -3], :Workshop, :Clothiers, nil))
addTask(BuildStockpileTask.new('cl_decoratable', ['dig_industry_10'], [43, 7, -3], 2, 6, 'cl_decoratable', false, false))
addTask(BuildTask.new('dyers', ['dig_industry_10'], [34, 8, -3], :Workshop, :Dyers, nil))
addTask(BuildTask.new('ashfurnace', ['dig_industry_10'], [23, 9, -3], :Furnace, :WoodFurnace, [{:JobType => :MakeAsh}]))
addTask(BuildStockpileTask.new('meals_drinks', ['dig_industry_2'], [26, 9, -3], 2, 12, 'mealsdrinks', true, false))
addTask(BuildTask.new('still1', ['dig_industry_2'], [28, 9, -3], :Workshop, :Still, [{:JobType => 211}]))
addTask(BuildStockpileTask.new('food', ['dig_industry_2'], [31, 9, -3], 3, 12, 'food', true, false))
addTask(BuildTask.new('loom', ['dig_industry_10'], [37, 9, -3], :Workshop, :Loom, [{:JobType => :WeaveCloth}]))
addTask(BuildTask.new('leatherworks', ['dig_industry_10'], [40, 10, -3], :Workshop, :Leatherworks, [{:JobType => :ConstructChest},{:JobType => :MakeFlask},{:JobType => :MakeQuiver},{:JobType => :MakeBackpack}]))
addTask(BuildStockpileTask.new('thread', ['dig_industry_10'], [34, 11, -3], 3, 1, 'thread', false, true))
addTask(BuildStockpileTask.new('ash', ['dig_industry_10'], [23, 12, -3], 3, 1, 'ash', false, false))
addTask(BuildTask.new('still2', ['dig_industry_10'], [28, 12, -3], :Workshop, :Still, [{:JobType => 211}]))
addTask(BuildStockpileTask.new('dye', ['dig_industry_10'], [34, 12, -3], 3, 1, 'dye', false, false))
addTask(BuildStockpileTask.new('leather', ['dig_industry_10'], [37, 12, -3], 3, 2, 'leather', false, true))
addTask(BuildStockpileTask.new('potash', ['dig_industry_10'], [21, 13, -3], 2, 3, 'potash', false, true))
addTask(BuildTask.new('ashery', ['dig_industry_10'], [23, 13, -3], :Workshop, :Ashery, [{:JobType => :MakePotashFromAsh},{:JobType => :MakeLye}]))
addTask(BuildTask.new('farmers', ['dig_industry_2'], [34, 13, -3], :Workshop, :Farmers, [{:JobType => :MilkCreature},{:JobType => :MakeCheese},{:JobType => 211},{:JobType => :ProcessPlants}]))
addTask(BuildTask.new('tanners', ['dig_industry_10'], [37, 14, -3], :Workshop, :Tanners, nil))
addTask(BuildTask.new('kitchen1', ['dig_industry_2'], [28, 15, -3], :Workshop, :Kitchen, [{:JobType => :PrepareMeal},{:JobType => 211}]))
addTask(BuildTask.new('boltcrafters', ['dig_industry_10'], [40, 15, -3], :Workshop, :Craftsdwarfs, [{:JobType => :MakeAmmo}]))
addTask(BuildStockpileTask.new('crossbow_goods', ['dig_industry_10'], [43, 15, -3], 2, 6, 'crossbow_goods', false, true))
addTask(BuildStockpileTask.new('lye', ['dig_industry_10'], [23, 16, -3], 3, 1, 'lye', false, false))
addTask(BuildStockpileTask.new('bags1', ['dig_industry_2'], [34, 16, -3], 3, 1, 'bags', false, false))
addTask(BuildTask.new('soapmaker', ['dig_industry_10'], [23, 17, -3], :Workshop, :Custom, [{:JobType => 211}]))
addTask(BuildStockpileTask.new('buckets', ['dig_industry_2'], [35, 17, -3], 2, 1, 'buckets', false, false))
addTask(BuildStockpileTask.new('hide', ['dig_industry_10'], [37, 17, -3], 3, 1, 'hide', false, false))
addTask(BuildTask.new('kitchen2', ['dig_industry_10'], [28, 18, -3], :Workshop, :Kitchen, [{:JobType => :PrepareMeal},{:JobType => 211}]))
addTask(BuildTask.new('butchers', ['dig_industry_2'], [34, 18, -3], :Workshop, :Butchers, nil))
addTask(BuildStockpileTask.new('wood_or_bone', ['dig_industry_10'], [37, 18, -3], 3, 3, 'bone', false, true))
addTask(BuildTask.new('bowyers', ['dig_industry_10'], [40, 18, -3], :Workshop, :Bowyers, [{:JobType => :MakeWeapon, :ItemSubType => 6}]))
addTask(BuildStockpileTask.new('soap', ['dig_industry_10'], [23, 20, -3], 3, 1, 'soap', false, true))
addTask(BuildStockpileTask.new('hoof_etc', ['dig_industry_1'], [34, 22, -3], 3, 2, 'hoofetc', false, false))
addTask(BuildStockpileTask.new('mechanisms', ['dig_industry_1'], [37, 22, -3], 6, 2, 'mechanics_out', false, false))
addTask(BuildStockpileTask.new('stone', ['dig_industry_1'], [43, 22, -3], 2, 14, 'stone', false, false))
addTask(BuildStockpileTask.new('bars', ['dig_industry_11'], [26, 24, -3], 2, 12, 'bars', false, false))
addTask(BuildTask.new('forge1', ['dig_industry_11'], [28, 24, -3], :Workshop, :MetalsmithsForge, nil))
addTask(BuildTask.new('carpenters', ['dig_industry_1'], [31, 24, -3], :Workshop, :Carpenters, [{:JobType => :MakeBucket},{:JobType => :ConstructBin},{:JobType => :MakeCage},{:JobType => :ConstructBed},{:JobType => :ConstructSplint},{:JobType => :ConstructCrutch}]))
addTask(BuildTask.new('bonecrafters', ['dig_industry_10'], [34, 24, -3], :Workshop, :Craftsdwarfs, nil))
addTask(BuildTask.new('mechanics', ['dig_industry_1'], [37, 24, -3], :Workshop, :Mechanics, [{:JobType => :ConstructMechanisms}]))
addTask(BuildTask.new('stonecrafters1', ['dig_industry_1'], [40, 24, -3], :Workshop, :Craftsdwarfs, [{:JobType => 218, :ItemSubType => 12},{:JobType => :MakeGoblet}, {:JobType => :MakeCrafts}]))
addTask(BuildStockpileTask.new('ore', ['dig_industry_11'], [19, 27, -3], 2, 9, 'ore', false, false))
addTask(BuildStockpileTask.new('flux', ['dig_industry_11'], [21, 27, -3], 2, 9, 'flux', false, false))
addTask(BuildTask.new('smelter1', ['dig_industry_11'], [23, 27, -3], :Furnace, :Smelter, nil))
addTask(BuildTask.new('forge2', ['dig_industry_11'], [28, 27, -3], :Workshop, :MetalsmithsForge, nil))
addTask(BuildStockpileTask.new('undecoratable', ['dig_industry_11'], [31, 27, -3], 2, 6, 'undecoratable', false, false))
addTask(BuildStockpileTask.new('decoratable', ['dig_industry_11'], [33, 27, -3], 7, 6, 'decoratable', false, false))
addTask(BuildTask.new('stonecrafters2', ['dig_industry_1'], [40, 27, -3], :Workshop, :Craftsdwarfs, [{:JobType => 218, :ItemSubType => 12},{:JobType => 218, :ItemSubType => 10}, {:JobType => :MakeCrafts}]))
addTask(BuildTask.new('smelter2', ['dig_industry_11'], [23, 30, -3], :Furnace, :Smelter, nil))
addTask(BuildTask.new('forge3', ['dig_industry_11'], [28, 30, -3], :Workshop, :MetalsmithsForge, nil))
addTask(BuildTask.new('masons1', ['dig_industry_10'], [40, 30, -3], :Workshop, :Masons, [{:JobType => :ConstructMillstone}, {:JobType => :ConstructCabinet}, {:JobType => :ConstructTable}, {:JobType => :ConstructSlab}, {:JobType => :ConstructWeaponRack}]))
addTask(BuildTask.new('smelter3', ['dig_industry_11'], [23, 33, -3], :Furnace, :Smelter, nil))
addTask(BuildTask.new('forge4', ['dig_industry_11'], [28, 33, -3], :Workshop, :MetalsmithsForge, nil))
addTask(BuildTask.new('kiln', ['dig_industry_11'], [31, 33, -3], :Furnace, :Kiln, nil))
addTask(BuildTask.new('glassfurnace1', ['dig_industry_11'], [34, 33, -3], :Furnace, :GlassFurnace, nil))
addTask(BuildTask.new('jewelsetters', ['dig_industry_11'], [37, 33, -3], :Workshop, :Jewelers, nil))
addTask(BuildTask.new('masons2', ['dig_industry_10'], [40, 33, -3], :Workshop, :Masons, [{:JobType => :ConstructDoor}, {:JobType => :ConstructBlocks}, {:JobType => :ConstructChest}, {:JobType => :ConstructThrone}, {:JobType => :ConstructCoffin}, {:JobType => :ConstructArmorStand}]))
addTask(BuildStockpileTask.new('ballista_arrowheads', ['dig_industry_11'], [25, 36, -3], 3, 1, 'ballista_arrowheads', false, false))
addTask(BuildStockpileTask.new('fuel', ['dig_industry_11'], [28, 36, -3], 3, 3, 'fuel', false, false))
addTask(BuildStockpileTask.new('clay', ['dig_industry_11'], [31, 36, -3], 3, 1, 'clay', false, false))
addTask(BuildStockpileTask.new('raw_glass', ['dig_industry_11'], [34, 36, -3], 3, 1, 'raw_glass', false, false))
addTask(BuildStockpileTask.new('cut_gems', ['dig_industry_11'], [37, 36, -3], 3, 2, 'gem_cut', false, false))
addTask(BuildStockpileTask.new('siege_goods', ['dig_industry_11'], [21, 37, -3], 2, 5, 'siege_out', false, false))
addTask(BuildTask.new('siege', ['dig_industry_11'], [23, 37, -3], :Workshop, :Siege, nil))
addTask(BuildTask.new('glassfurnace2', ['dig_industry_11'], [34, 37, -3], :Furnace, :GlassFurnace, nil))
addTask(BuildStockpileTask.new('pearlash', ['dig_industry_11'], [31, 38, -3], 3, 1, 'pearlash', false, false))
addTask(BuildTask.new('jewelcutters', ['dig_industry_11'], [37, 38, -3], :Workshop, :Jewelers, nil))
addTask(BuildStockpileTask.new('rough_gems', ['dig_industry_11'], [40, 38, -3], 5, 4, 'gem_rough', false, false))
addTask(BuildTask.new('fuelfurnace1', ['dig_industry_11'], [28, 39, -3], :Furnace, :WoodFurnace, nil))
addTask(BuildTask.new('fuelfurnace2', ['dig_industry_11'], [31, 39, -3], :Furnace, :WoodFurnace, nil))
addTask(BuildStockpileTask.new('bags2', ['dig_industry_11'], [34, 40, -3], 3, 1, 'bags', false, false))
addTask(BuildStockpileTask.new('sand', ['dig_industry_11'], [34, 41, -3], 3, 1, 'sand', false, false))


addTask(BuildStockpileTask.new('refuse', ['dig_entrance_3'], [26, 14, -4], 1, 1, 'refuse', false, false))
addTask(BuildCivZoneTask.new('dogs', ['dig_entrance_1'], [9, 15, -4], 1, 1, :Pasture, 157))
addTask(BuildTask.new('refuse_door', ['dig_entrance_3'], [31, 18, -4], :Door, nil, nil))
addTask(BuildTask.new('depot', ['dig_entrance_1'], [9, 21, -4], :TradeDepot, nil, nil))
addTask(BuildStockpileTask.new('tradeable', ['dig_entrance_1'], [14, 21, -4], 1, 1, 'tradeable', false, true))
addTask(DigTask.new("dig_entrance_1", ["dig_industry_1"], [0, 0, -4], "entrance.csv", 1))
addTask(DigTask.new("dig_entrance_2", ["dig_industry_3"], [0, 0, -4], "entrance.csv", 2))
addTask(DigTask.new("dig_entrance_3", ["dig_entrance_1"], [0, 0, -4], "entrance.csv", 3))
addTask(DigTask.new("dig_entrance_4", ["dig_entrance_1"], [0, 0, -4], "entrance.csv", 4))
addTask(DigTask.new("dig_entrance_5", ["dig_entrance_1"], [0, 0, -4], "entrance.csv", 5))
addTask(BuildStockpileTask.new('refuse', ['dig_entrance_3'], [26, 14, -4], 5, 5, 'refuse', false, false))
addTask(BuildCivZoneTask.new('dogs', ['dig_entrance_1'], [9, 15, -4], 5, 5, :Pasture, 157))
addTask(BuildTask.new('depot', ['dig_entrance_1'], [9, 21, -4], :TradeDepot, nil, nil))
addTask(BuildStockpileTask.new('tradeable', ['dig_entrance_1'], [14, 21, -4], 5, 5, 'tradeable', false, true))


addTask(BuildTask.new('c1', ['dig_dining_3'], [14, 17, -5], :Chair, nil, nil))
addTask(BuildTask.new('t1', ['dig_dining_3'], [15, 17, -5], :Table, nil, nil))
addTask(BuildTask.new('c5', ['dig_dining_3'], [16, 17, -5], :Chair, nil, nil))
addTask(BuildTask.new('c2', ['dig_dining_3'], [14, 18, -5], :Chair, nil, nil))
addTask(BuildTask.new('t2', ['dig_dining_3'], [15, 18, -5], :Table, nil, nil))
addTask(BuildTask.new('c6', ['dig_dining_3'], [16, 18, -5], :Chair, nil, nil))
addTask(BuildTask.new('c3', ['dig_dining_3'], [14, 19, -5], :Chair, nil, nil))
addTask(BuildTask.new('t3', ['dig_dining_3'], [15, 19, -5], :Table, nil, nil))
addTask(BuildTask.new('c7', ['dig_dining_3'], [16, 19, -5], :Chair, nil, nil))
addTask(BuildTask.new('c4', ['dig_dining_3'], [14, 20, -5], :Chair, nil, nil))
addTask(BuildTask.new('t4', ['dig_dining_3'], [15, 20, -5], :Table, nil, nil))
addTask(BuildTask.new('c8', ['dig_dining_3'], [16, 20, -5], :Chair, nil, nil))
addTask(DigTask.new("dig_dining_1", ["dig_entrance_1"], [0, 0, -5], "dining.csv", 1))
addTask(DigTask.new("dig_dining_2", ["dig_dining_1"], [0, 0, -5], "dining.csv", 2))
addTask(DigTask.new("dig_dining_3", ["dig_entrance_3"], [0, 0, -5], "dining.csv", 3))


addTask(BuildConstructionTask.new('vwall', ['dig_caverns_3'], [25, 26, -10], :Wall, 1, 1))
addTask(BuildTask.new('vcagetrap1', ['dig_caverns_1'], [25, 30, -10], :Trap, :CageTrap, nil))
addTask(BuildTask.new('vcagetrap2', ['dig_caverns_1'], [25, 31, -10], :Trap, :CageTrap, nil))
addTask(DigTask.new("dig_caverns_1", ["stairs-9"], [0, 0, -10], "caverns.csv", 1))
addTask(DigTask.new("dig_caverns_2", ["vcagetrap1","vcagetrap2","vcagetrap3","vcagetrap4","vcagetrap5","vcagetrap6"], [0, 0, -10], "caverns.csv", 2))
addTask(DigTask.new("dig_caverns_3", ["dig_caverns_2"], [0, 0, -10], "caverns.csv", 3))


